# Generated by Django 3.2.4 on 2021-08-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estetico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='specialist',
        ),
    ]
