# Generated by Django 3.2.4 on 2021-08-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estetico', '0003_special_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special', to='estetico.specialist', verbose_name='Мнение специалиста'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='estetico.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
