# Generated by Django 3.2.4 on 2021-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetico', '0004_special_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='text',
            field=models.CharField(max_length=250, null=True, verbose_name='Текст под скидкой'),
        ),
    ]
