# Generated by Django 3.2.4 on 2021-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetico', '0005_alter_special_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='price',
            field=models.CharField(max_length=200, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
