# Generated by Django 3.2.4 on 2021-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetico', '0006_alter_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
