# Generated by Django 3.2.4 on 2021-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetico', '0007_alter_special_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='map',
            field=models.TextField(null=True, verbose_name='Код карты'),
        ),
    ]
