# Generated by Django 3.2.4 on 2021-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('image', models.ImageField(upload_to='images/blog', verbose_name='Изображение')),
                ('slug', models.SlugField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
